### ISSUE TITLE
not support multi ebean server

### ISSUE THREAD

**Issue by icode** [ebean-orm/avaje-ebeanorm-jackson#2]
default use Ebean.json(),how to use multi ebean server?

**Comment by rbygrave** [comment]
The JacksonEbeanModule constructor that takes a jsonContext ... which is the jsonContext from an EbeanServer.

So the answer is ... use this constructor.

``` java

  public JacksonEbeanModule(JsonContext jsonContext) {
    this.jsonContext = jsonContext;
  }

```

**Comment by rbygrave** [comment]
Reopen this issue if required.
